name: complete LXD build

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/complete_lxd_build.yml"
      - "scripts/**"
      - "images/ubuntu/**"
      - "patches/**"

  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/complete_lxd_build.yml"
      - "scripts/**"
      - "images/ubuntu/**"
      - "patches/**"

  workflow_dispatch:


jobs:
  gaplib-build:
    name: Run complete build - ${{ matrix.runner_name }} [${{ matrix.runner_owner }}]
    runs-on: ${{ matrix.runner_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: "ubuntu"
            version: "24.04"
            runner_name: "ubuntu-24.04-ppc64le"
            runner_owner: "ppc64le-hosted"
            setup_type: "complete"
          - os: "ubuntu"
            version: "24.04"
            runner_name: "ubuntu-24.04-s390x"
            runner_owner: "s390x-hosted"
            setup_type: "complete"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Build Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: | 
          scripts/lxd_container.sh "${{ matrix.os }}" "${{ matrix.version }}" "" "" "${{ matrix.setup_type }}" --skip-snap-lxd --skip-lxd-snapshot 
